name: CI - Last Ontology Build

on:
  repository_dispatch:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
      - name: Create LinkML schema from the project s googlesheet of metadata
        run: |
          docker run --rm -v $(pwd):/workdir -u $(id -u):$(id -g) evoratools/schemasheets:0.3.1 \
          sheets2linkml --gsheet-id 1zcyNKuhkpH-0FqEGSt6UwHAiSYzsUUSkHYcDOYz67zI \
          --name EVORA CompleteList Prefixes \
          -o models/evora_schema.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: evora-schema.yaml
          path: models/evora_schema.yaml
          compression-level: 9 # maximum compression
    
      - name: Generate project owl ttl file with LinkML 
        run: |
          docker run --rm -v $(pwd):/workdir -u $(id -u):$(id -g) evoratools/schemasheets:0.3.1 \
          linkml generate owl models/evora_schema.yaml > models/owl/evora_ontology.owl.ttl
          
      - uses: actions/upload-artifact@v4
        with:
          name: evora-ontology.owl.ttl
          path: models/owl/evora_ontology.owl.ttl
          compression-level: 9 # maximum compression

      - name: Generate project owl ttl file with LinkML 
        run: |
          docker run --rm -v $(pwd):/workdir -u $(id -u):$(id -g) evoratools/schemasheets:0.3.1 \
          linkml generate project -d models models/evora_schema.yaml 


      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: "CI Build: Synchronisation with google sheet metadata"
          CI_COMMIT_AUTHOR: GithubAction CI
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add evora_ontology.owl evora_schema.yaml
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
        
