name: CI - Merge from staging

on:
  repository_dispatch:
  workflow_dispatch:
      inputs:
          version:
              description: 'Google Sheet metadata file version asking for Sync'
              required: false
              type: string

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
          commit-message: Merge last schema models build from staging
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: main
          delete-branch: false
          title: 'Merge last schema models build from staging'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: Angatar
          reviewers: Angatar
          team-reviewers: |
            developers
            qa-team
          milestone: 1
          draft: false
